server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-10524233.okta.com/oauth2/default
    audience: api://default
    client-id: 0oah7xjp9accaepzj5d7
    client-secret: TTCx3tf49b7XqzpKu1xPX7MitaqwT1WcEddPFM9Po5sdamxYq-0kN5HR2LyKYbi_
    scopes: openid, profile, email, offline_access